from django.shortcuts import render

def chain_rule_lesson(request):
    vtitle = 'Chain Rule Lesson - Calculus College'
    meta_des = 'The chain rule does not have to be a mystery. Learn how to apply the chain rule like a machine and never worry about it again.'
    vLessonTitle = 'Learn the Chain Rule'
    vFormal = "<h3 style='font-size:22px;'>$\\frac{d}{dx}[f(g(x))]=f'(g(x))g'(x)$</h3>"
    vInformal = 'Multiply the derivative of the outside function (evaluated at the inside function) by the derivative of the inside function.'
    vLinks = [{'href':'chain_rule_worksheet.html','title':'Chain Rule Worksheet','description':"Work as many problems as you need. They're broken into many categories for your pleasure."}]
    vLinks.append({'href':'http://tutorial.math.lamar.edu/Classes/CalcI/ChainRule.aspx','title':'Chain Rule','description':"Paul's Notes provides an in-depth explanation of the chain rule."})
    vLinks.append({'href':'https://www.youtube.com/watch?v=6kScLENCXLg','title':'Chain Rule for Finding Derivatives','description':'PatrickJMT provides a relatively quick video explaining the chain rule.'})
    vFlowchart = 'static/img/chain_rule_flowchart.png'
    vparts = [{'header':'When do we use the chain rule?','text':'Can any other rule be applied to the function? If not, then it is likely time to use the chain rule. If the function does not seem to be a <a href="product_rule_lesson.html">product</a>, <a href="quotient_rule_lesson.html">quotient</a>, or <a href="sum_rule_lesson.html">sum</a> of simpler functions then the best bet is trying to decompose the function to see if the chain rule works.<p><br> To be more precise, if the function is the composition of two simpler functions then the chain rule is necessary. If you are pretty sure that nothing else can be done, then go ahead and try the chain rule. Every function can be written as a composition, but the chain rule only helps when the inside function is not simply $x$.'}]
    vparts.append({'header':'How do we decompose a function?','text':'<p>The hard part is usually dealing with the composition of functions, but with enough experience it will become obvious how to decompose a function for the chain rule. I usually give students vague advice about knowing it when they see it and most humans are able to figure it out most of the time. But when programming I cannot tell the computer that it should pick the obvious inside function. So here is the basic idea of how I taught the computer to apply the chain rule. It really boils down to check a few straightforward cases that come up.</p> <p>First, identify the outside function. This is easy because there are only a few options available for the outside function. Assuming you have already stripped away everything except the composition the outside function must be one of the four basic functions we discussed earlier. Look for a <a href="trigonometric_functions_lesson.html">trigonometric</a>, <a href="exponentials_logarithms_lesson.html">exponential</a>, <a href="exponentials_logarithms_lesson.html">logarithmic</a>, or <a href="power_rule_lesson.html">power</a> function. There might be something messy on the inside, but the outside will be the same every time.</p><p>Does the function look like $\sin(......)$ where the ...... can be any function of $x$? Does it look like another trigonometric or inverse trigonometric function on the outside--i.e. $\cos(......)$ or $\\tan^{-1}(......)$ or the other 9 possible functions? If so, you have identified the outside function and whatever is on the inside is your inside function.</p><p>Does the function look like $\ln(......)$ or $\log_b(......)$ or $e^{(......)}$ or $b^{(......)}$? If so, use the same approach as with the trig function. Does the function look like $(......)^c$? Again the ...... will be the inside function and $x^c$ will be the outside function.'})
    vparts.append({'header':'How do we apply the chain rule?','text':'Once you have identified the two functions then it is time to differentiate. Differentiate each function separately. Then be careful with the outside function and evaluate it at the inside function. This sounds harder than it is. Just plug in the inside function to the derivative of the outside function. Then multiply that derivative by the derivative of the inside function. <a href="derivative_calculator.html">See it in action</a> with our calculator until you get the hang of it.'})
    vparts.append({'header':'Why is the notation so confusing?','text':'The chain rule is a little awkward because the independent variable $x$ can be reused in different functions. Or a different variable like $u$ can be used. Either way might seem weird to you, but since there are three different functions to deal with (the original, the outside, and the inside) there are multiple independent variables required.<p> Ultimately $f(u)=u^2+1$ and $f(x)=x^2+1$ are the same thing because the variable is irrelevant. The independent variable of the outside function will be replaced by a function of $x$, and often letting $u$ represent this inside function is the easiest thing to do because $f\'(u)$ is more intuitive than $f\'(\sin(x))$ or whatever may be inside.'})
    vparts.append({'header':'What are the most common mistakes?','text':'Make sure you correctly decompose the function. If you do not properly break the function into two parts then the chain rule will not yield a correct derivative. Make sure that you correctly differentiate each function. Do not speed through this process, and pay attention to where you are evaluating the outside function.'})
    next_lesson = 'A lesson on <a href="logarithmic_differentiation_lesson.html">Logarithmic Differentiation</a>'
    return render(request,'base_lesson.html',{'title':vtitle,'meta_des':meta_des,'LessonTitle':vLessonTitle,'Next':next_lesson,'Formal':vFormal,'Informal':vInformal,'Links':vLinks,'Flowchart':vFlowchart,'parts':vparts})
