from django.shortcuts import render

def how_to_differentiate_lesson(request):
    vtitle = 'How to Take Derivatives - Calculus College'
    meta_des = 'We created a derivative calculator and will teach you all the tricks it uses to compute derivatives. Learn the process that works for every function.'
    vLessonTitle = 'How to take any derivative'
    vInformal = 'Try every rule until something works.'
    vFormal = 'Is the function one of the basic functions? If yes, take the derivative. If not, apply the right rule to break the function into two simpler functions to differentiate.'
    vLinks = [{'href':'https://www.math.brown.edu/UTRA/derivtips.html','title':'Tips for Derivatives','description':"The Brown University math department provides valuable advice on how to differentiate functions."}]
    vLinks.append({'href':'https://www.youtube.com/watch?v=L6IzEuTpi48','title':'Everything you need to know about taking derivatives in 20 minutes','description':'Carter Bowles provides a video where he works through all types of derivatives to explain his process.'})
    vLinks.append({'href':'http://www.wikihow.com/Take-Derivatives','title':'How to Take Derivatives','description':'WikiHow does a decent job of quickly explaining the steps involved in differentiation.'})
    vFlowchart = 'static/img/how_to_differentiate_flowchart.png'
    vparts = [{'header':'How do we take derivatives?','text':'There are two important parts of differentiation that every student needs to learn. The first part is the ability to differentiate basic functions. The second part is the ability to apply four rules that allow you to break complicated functions into two simpler functions. This process is simple, but may need to be repeated multiple times and students need to be careful to keep track of exactly what they are doing. <p><br> Whenever you are asked to differentiate a function the approach is the same. First, check if you know the derivative of the function. If so you are done. If not then use the sum, product, quotient, or chain rule to simplify the function until you get to a function that you know how to differentiate. This will work every time.'}]
    vparts.append({'header':'What is the first step?','text':'You need to be able to quickly differentiate a few types of functions. There are three rules to learn as well as remembering how to differentiate twelve trigonometric functions. These function are the basis of every more complicated function so it is vital that you learn how to recognize and differentiate these. The next three lessons cover <a href="power_rule_lesson.html">power</a>, <a href="exponentials_logarithms_lesson.html">exponential, logarithmic</a>, and <a href="trigonometric_functions_lesson.html">trigonometric</a> functions in depth.'})
    vparts.append({'header':'What if the function is not so basic?','text':'If the function is not so simple then we need to break it down until we reach functions that can be differentiated in the previous step. We can apply the <a href="sum_rule_lesson.html">sum</a>, <a href="product_rule_lesson.html">product</a>, <a href="quotient_rule_lesson.html">quotient</a>, or <a href="chain_rule_lesson.html">chain</a> rule to break it up. We may need to do this more than once, but in each step our goal is just to make the problem simpler. As long as we track what we are doing then we will be able to fully decompose any complex function one rule at a time.'})
    next_lesson = 'A lesson on the <a href="power_rule_lesson.html">Power Rule</a>'
    return render(request,'base_lesson.html',{'title':vtitle,'meta_des':meta_des,'LessonTitle':vLessonTitle,'Next':next_lesson,'Formal':vFormal,'Informal':vInformal,'Links':vLinks,'Flowchart':vFlowchart,'parts':vparts})
