from django.shortcuts import render

def implicit_differentiation_lesson(request):
	vtitle = 'Implicit Differentiation Lesson - Calculus College'
	meta_des = "What is implicit differentiation, when is it used, and how do we do it? Learn how to find a derivative when you cannot directly solve for y. "
	vLessonTitle = 'Learn Implicit Differentiation'
	vFormal = '<h3 style="font-size:18px;">$\\frac{d}{dx}[y]=\\frac{dy}{dx}$<br>$\\frac{d}{dx}[f(y)]=\\frac{d}{\\textbf{dy}}[f(y)]\\frac{dy}{dx}$</h3>'
	vInformal = 'Treat $y$ as a function of $x$ and apply the chain rule every time $y$ appears. Then solve for $\\frac{dy}{dx}$.'
	vLinks = [{'href':'http://tutorial.math.lamar.edu/Classes/CalcI/ImplicitDIff.aspx','title':'Implicit Differentiation','description':"Paul's Notes provides an in-depth explanation of implicit differentiation with several examples worked through in detail."}]
	vLinks.append({'href':'https://www.math.ucdavis.edu/~kouba/CalcOneDIRECTORY/implicitdiffdirectory/ImplicitDiff.html','title':'Implicit Differentiation','description':"UC Davis has a few examples to test your understanding of taking derivatives implicitly."})
	vLinks.append({'href':'https://www.khanacademy.org/math/ap-calculus-ab/advanced-differentiation-ab/implicit-differentiation-intro-ab/v/implicit-differentiation-1','title':'Implicit Differentiation','description':"A Khan Academy video that explains implicit differentiation with a standard circle example."})
	vFlowchart = 'static/img/implicit_differentiation_flowchart.png'
	vparts = [{'header':'When do we use implicit differentiaion?','text':'When an equation is not solved for $y$ then try to solve for $y$. However, if it is not possible to solve for $y$ and we are asked to find $\\frac{dy}{dx}$ then it is time to use implicit differentiation. We will be able to find the derivative, but only at the cost of being slightly more involved. Normally we expect the derivative to be a function of $x$, but with implicit differentiation the derivative will be a function of both $x$ and $y$.'}]
	vparts.append({'header':'How do we use implicit differentiation?','text':'Take the derivative of both sides of the equation. Be careful whenever $y$ appears to treat it as a function of $x$ and correctly apply the chain rule. The expression $\\frac{dy}{dx}$ will appear every time you differentiate $y$, and the next step is to solve for $\\frac{dy}{dx}$. Collect all of the $\\frac{dy}{dx}$ on one side and factor it out before dividing. Solving for $\\frac{dy}{dx}$ should be easy since the equation will be linear with respect to $\\frac{dy}{dx}$. Then you have the derivative you are seeking without ever knowing what $y$ actually is as a function of $x$. Although the function iwll depend on $x$ and $y$ so you will need to know both coordinates to compute the derivative at a particular point.'})
	vparts.append({'header':'Can I see an example?','text':'Suppose $\sin(y)=x$ and we want to find $\\frac{dy}{dx}$. One possibility for this problem is to solve for $y$ and then use <a href="trigonometric_functions_lesson.html">the derivative of arcsine</a>, which you should have memorized. However, we should get the same result if we do it implicitly.<br><p><br> Take the derivative of both sides. We can <a href="chain_rule_lesson.html">apply the chain rule</a> with $y$ as the inside function and sine as the outside to get $\\frac{d}{dx}[\sin(y)]=\cos(y)\\frac{d}{dx}[y]=\cos(y)\\frac{dy}{dx}$ and it should be obvious that $\\frac{d}{dx}[x]=1$. Thus after differentiation we have $\cos(y)\\frac{dy}{dx}=x$.<br><p> Solving for $\\frac{dy}{dx}$ is easy since we just divide by $\cos(y)$ to yield $\\frac{dy}{dx}=\\frac{x}{\cos(y)}$. This derivative does not look like the derivative you memorized for arcsine, so what is the difference?<br><p> This derivative still depends on $y$, but we will try to replace $\cos(y)$ with a function of $x$. We are lucky with this example and can actually rewrite $\cos(y)$ as $\sqrt{1-x^2}$ since $\cos^2(y)+\sin^2(y)=1$ and we know what $\sin(y)$ is. Now using $\sqrt{1-x^2}$ as the denominator makes our answer look familiar. Although this example did not require implicit differentation it is always good to see that our new methods match what we expect from old methods.'})
	vparts.append({'header':'One more example?','text':'What if we make it a bit more complicated so that we cannot solve for $y$? Find $\\frac{dy}{dx}$ when $y\sin(y)=x$. Now the derivative will have to depend on $y$.<br><p><br> <a href="how_to_differentiate_lesson.html">Taking the derivative of</a> both sides is again easy on the right side, but the left requires a product and chain rule so be careful. Using <a href="product_rule_lesson.html">the product rule</a>, $$\\frac{d}{dx}[y\sin(y)]=y\\frac{d}{dx}[\sin(y)]+\sin(y)\\frac{d}{dx}[y].$$ We already found derivatives of $\sin(y)$ and $y$ so plug them in to get $$\\frac{d}{dx}[y\sin(y)]=y\\frac{d}{dx}[\sin(y)]+\sin(y)\\frac{d}{dx}[y]=y\cos(y)\\frac{dy}{dx}+\sin(y)\\frac{dy}{dx}=\\frac{dy}{dx}(y\cos(y)+\sin(y)).$$<br><p> The last thing we did was factor out the $\\frac{dy}{dx}$ so that we can divide. The right side was agian 1 so after dividing we get our answer $\\frac{dy}{dx}=\\frac{1}{y\cos(y)+\sin(y)}$. Since we do not know what $\sin(y)$ or $y\cos(y)$ are we cannot go any further and must leave our answer in this form.  '})
	
	next_lesson = 'Learn when functions <a href="increasing_decreasing_lesson.html">increase and decrease.</a>'
	return render(request,'base_lesson.html',{'title':vtitle,'meta_des':meta_des,'LessonTitle':vLessonTitle,'Next':next_lesson,'Formal':vFormal,'Informal':vInformal,'Links':vLinks,'Flowchart':vFlowchart,'parts':vparts})

def increasing_decreasing_lesson(request):
	vtitle = 'Increasing and Decreasing Functions - Calculus College'
	meta_des = "How do we determine when a function is increasing or decreasing? Learn how to use derivatives to determine the intervals on which a function increases."
	vLessonTitle = 'Increasing and Decreasing'
	vFormal = "<h3 style='font-size:16px;'>If $f'(x)>0$ then $f$ is increasing at $x$.</h3>"
	vInformal = 'A function is increasing when its derivative is positive and decreasing when the derivative is negative.'
	vLinks = [{'href':'https://www.khanacademy.org/math/algebra/algebra-functions/positive-negative-increasing-decreasing-intervals/v/increasing-decreasing-positive-and-negative-intervals','title':'Increasing and Decreasing Intervals','description':"A Khan Academy video explains how to use Calculus to find increasing and decreasing intervals."}]
	vLinks.append({'href':'http://www.coolmath.com/precalculus-review-calculus-intro/precalculus-algebra/11-graphing-increasing-decreasing-01','title':'Increasing and Decreasing of Functions','description':"CoolMath explains the basics of what it means for a function to be increasing or decreasing."})
	vLinks.append({'href':'https://www.youtube.com/watch?v=ge9Jv0t_QNY','title':'Increasing-Decreasing Functions','description':"Dr. Ford provides a video describing how to find when a function is increasing or decreasing."})
	vFlowchart = 'static/img/increasing_decreasing_flowchart.png'
	vparts = [{'header':'When is a function increasing?','text':'A function is considered increasing on an interval whenever <a href="how_to_differentiate_lesson.html">the derivative</a> is positive over that interval. And the function is decreasing on any interval in which the derivative is negative.'}]
	vparts.append({'header':'How do we determine the intervals?','text':"The first step is to <a href='all_derivatives_worksheet.html'>take the derivative of the function</a>. Then solve for any points where the derivative equals 0. That is, solve for all $x$ such that $f'(x)=0$. Then we need to find any points where the derivative is undefined, so we set the denominator of $f'(x)$ equal to 0 and solve for all such values of $x$. These values of $x$ will form the endpoints of potential intervals."})
	vparts.append({'header':'How do we know if the function is increasing on an interval?','text':"Once the intervals are established we must determine whether the derivative is positive or negative on each interval. The simplest thing to do is to plug in any value in that interval into the derivative and see if the output is positive or negative. Any value on an interval should have the same sign so choose the value that is easiest to plug in. You don't have to actually find the derivative just figure out if it is positive or negative. Be careful to plug into the derivative and not the original function."})
	
	next_lesson = 'Take <a href="second_derivatives_lesson.html">second derivatives.</a>'
	return render(request,'base_lesson.html',{'title':vtitle,'meta_des':meta_des,'LessonTitle':vLessonTitle,'Next':next_lesson,'Formal':vFormal,'Informal':vInformal,'Links':vLinks,'Flowchart':vFlowchart,'parts':vparts})

def second_derivatives_lesson(request):
	vtitle = 'Second Derivatives Lesson - Calculus College'
	meta_des = "How do we find the second derivative of a function? Why is it important to take the second derivative? Learn all you need to know at Calculus College."
	vLessonTitle = 'The Second Derivative'
	vFormal = "<h3 style='font-size:16px;'>$f''(x)=\\frac{d}{dx}[\\frac{d}{dx}[f(x)]]$</h3>"
	vInformal = 'Take the first derivative and then just take the derivative of that derivative.'
	vLinks = [{'href':'https://www.youtube.com/watch?v=3aVT9d_RTsk','title':'How to find second derivative','description':"A short video that finds the second derivative of a function."}]
	vLinks.append({'href':'https://en.wikipedia.org/wiki/Second_derivative','title':'Second Derivative','description':"The Wikipedia article about the second derivative of a function."})
	vLinks.append({'href':'http://math.ucr.edu/home/baez/physics/General/jerk.html','title':'Third Derivative of Position','description':"Some interesting information about third and further derivatives of the position function."})
	vFlowchart = 'static/img/second_derivatives_flowchart.png'
	vparts = [{'header':'How do we take the second derivative?','text':'Assuming you know <a href="how_to_differentiate_lesson.html">how to take the first derivative</a>, the second derivative really is not anything new. Take the derivative as you normally do. Then you may wish to simplify this derivative if possible to make the next step easier. Finally, take the derivative of the derivative in the same way as you would any other function. Now you have the second derivative.'}]
	vparts.append({'header':'Why do we take the second derivative?','text':'The second derivative identifies the <a href="concavity_lesson.html">concavity</a> of the function. Concavity determines whether a function is at a maximum or minimum. As we will see <a href="">later</a>, the second derivative gives the acceleration of a function. Also, second and higher power derivatives are important in Taylor series in future Calculus classes.'})
	vparts.append({'header':'What about third derivatives and beyond?','text':'Derivatives beyond the second derivative do have applications and are no more complicated. The third derivative, as expected, is found by taking the derivative of the second derivative. In general there is no way to find these derivatives without differentiating the full series of derivatives.<br><p><br> However, some functions have very predictable patterns for multiple derivatives. The easiest case is <a href="exponentials_logarithms_lesson.html">the exponential function</a>. What is the $12^{th}$ derivative of $e^x$? The second derivative is $e^x$ so the third derivative is as well and this pattern continues forever so the $12^{th}$ derivative is the same as the first and thousandth derivatives.<br><p>What about <a href="trigonometric_functions_lesson.html">trigonometric functions</a>? Take a few derivatives of $\sin(x)$ and try to identify the pattern. Since the derivatives of sine and cosine swap with an extra negative, any further derivative will either be $\pm\sin(x)$ or $\pm\cos(x)$ and you should work out when it is each of these.<br><p> For <a href="power_rule_lesson.html">power functions</a>, the exponent will decrease by one each time until the derivative becomes $0$ at which point any further derivative will also be $0$. Can you develop a formula for the coefficient of the $k^{th}$ derivative of $x^n$?'})
	vparts.append({'header':'Can I get one example?','text':'The second derivative is only harder than the first derivative because it requires two derivatives and the derivative function will likely be at least a little complicated.<br><p><br> A relatively simple example is to take the second derivative of $x\ln(x)$. The first derivative is $\ln(x)+1$ from the product rule. Then the second derivative is $\\frac{1}{x}$ since we know the derivatives of $\ln(x)$ and $1$.'})
	next_lesson = 'Learn about <a href="concavity_lesson.html">concavity.</a>'
	return render(request,'base_lesson.html',{'title':vtitle,'meta_des':meta_des,'LessonTitle':vLessonTitle,'Next':next_lesson,'Formal':vFormal,'Informal':vInformal,'Links':vLinks,'Flowchart':vFlowchart,'parts':vparts})

def concavity_lesson(request):
	vtitle = 'Concavity Lesson - Calculus College'
	meta_des = "How do we determine when a function is concave up or down? What does the concavity of a function tell us? Learn how to use second derivatives to analyze a function."
	vLessonTitle = 'All About Concavity'
	vFormal = "<h3 style='font-size:16px;'>If $f''(x)>0$ then $f$ is concave up at $x$.</h3>"
	vInformal = 'Geometrically, a function is concave up when the tangents to the curve are below the graph of the function. Using Calculus to determine concavity, a function is concave up when its second derivative is positive and concave down when the second derivative is negative.'
	vLinks = [{'href':'https://www.math.hmc.edu/calculus/tutorials/secondderiv/','title':'Concavity','description':"Harvey Mudd College explains how concavity and the sceond derivative are related."}]
	vLinks.append({'href':'http://tutorial.math.lamar.edu/Classes/CalcI/ShapeofGraphPtII.aspx','title':'The Shape of a Graph','description':"Paul's Notes explains in-depth how the shape of a graph is impacted by the second derivative."})
	vLinks.append({'href':'https://www.youtube.com/watch?v=DEBbLyqF8t0','title':'How to Find Concavity','description':"This video works a simple example of finding concavity using the second derivative."})
	vFlowchart = 'static/img/concavity_flowchart.png'
	vparts = [{'header':'When is a function concave up?','text':'When the second derivative of a function is positive then the function is considered concave up. And the function is concave down on any interval where the second derivative is negative.'}]
	vparts.append({'header':'How do we determine the intervals?','text':"First, find the <a href='second_derivatives_lesson.html'>second derivative</a>. Then solve for any points where the second derivative is 0. That is, find all $x$ such that $f''(x)=0$. We also need to consider any values that make the second derivative undefined, so if there is a denominator check when it is 0 and add any of these values to our list. These values will be the possible endpoints of the intervals we want to consider."})
	vparts.append({'header':'Which intervals are concave up?','text':"Inside each interval the second derivative is either positive or negative for the entire interval since we know it does not cross 0 within the interval. Therefore we just need to check whether the second derivative is positive or negative for one value from each interval. So pick the value inside each interval that is easiest to plug in and determine if the second derivative is positive or negative. If it is positive then the function is concave up on that interval, and if the second derivative is negative then the function is concave down on that interval. Just be careful to plug into the correct function. Use the second derivative not the first derivative or the original function."})
	next_lesson = 'Find <a href="maximums_minimums_lesson.html">maximums and minimums</a>.'
	return render(request,'base_lesson.html',{'title':vtitle,'meta_des':meta_des,'LessonTitle':vLessonTitle,'Next':next_lesson,'Formal':vFormal,'Informal':vInformal,'Links':vLinks,'Flowchart':vFlowchart,'parts':vparts})

def maximums_minimums_lesson(request):
	vtitle = 'Maximums and Minimums - Calculus College'
	meta_des = "When does a function reach a maximum? Learn how to use derivatives to determine the maxmium and minimum points of a function."
	vLessonTitle = 'Maximums and Minimums'
	vFormal = "<h3 style='font-size:16px;'>$f$ has a local maximum when $f'(x)=0$ and $f''(x)<0$.</h3>"
	vInformal = 'For each critical point (points where the derivative is 0 or undefined) check whether the function is concave up for a minimum or concave down for a maximum.'
	vLinks = [{'href':'http://tutorial.math.lamar.edu/Classes/CalcI/MinMaxValues.aspx','title':'Minimum and Maximum Values','description':"Paul's Notes explains in-depth how derivatives are used to find the maximum and minimum values of a function."}]
	vLinks.append({'href':'http://clas.sa.ucsb.edu/staff/lee/Max%20and%20Min%27s.htm','title':"Max and Min's",'description':"UCSB has a quick lesson on maximums and minimums of a function."})
	vLinks.append({'href':'https://www.youtube.com/watch?v=votVWz-wKeI','title':'Local and Absolute Maximums','description':"PatrickJMT has a video that explains how to use the graph of a function to find maximum and minimum values."})
	vFlowchart = 'static/img/maximums_minimums_flowchart.png'
	vparts = [{'header':'What is a local maximum?','text':'A local maximum is a point where the function is larger at that point than it is in either direction. That is, for both slightly smaller and slightly larger values of $x$ the function is smaller. From what we know about increasing and decrasing functions, this means that the function is increasing on the left of the point and decreasing to the right. We are looking for where the function switches from increasing to decreasing so we use the same intervals.'}]
	vparts.append({'header':'How do I find Critical Points?','text':'Use the same process as finding <a href="increasing_decreasing_lesson.html">increasing and decreasing</a> intervals. Take the derivative and then find when the derivative is 0 or undefined (denominator equals 0). Make sure to set the derivative, not the original function, equal to 0. These are the critical points that we will check for maximums and minimums in the next step.'})
	vparts.append({'header':'How do we know if a critical point is a local maximum or minimum?','text':'We defined a local maximum as a point where the function switches from increasing on the left to decreasing on the right. So if we have already determined intervals of increasing and decreasing we simply look at the intervals surrounding the critical point. If they switch from increasing to decreasing then it is a local maximum. If they switch from decreasing to increasing then it is a local minimum. If the function is increasing on both sides or decreasing on both sides then the function does not have a max or min at this critical value.<br><p><br>If you have not already determined where the function is increasing and decreasing then you have two options. One is to determine these intervals and see where the functions switches from increaing to decreasing or vice versa. The other is the second derivative test.<br><p> If the second derivative is positive at the critical point then the function is concave up so the function has a local minimum. Of course, if the second derivative is negative then the function has a local maximum. Here positive means minimum and negative means maximum so to not be confused you should think about what concave up and down look like.<br><p> If you need to determine <a href="concavity_lesson.html">concavity</a> then you will need to <a href="second_derivative_lesson.html">find the second derivative</a> so you might as well use the second derivative test. If you are simply asked to find local maximums and minimums then you can pick either approach depending on which you are more comfortable with.'})
	vparts.append({'header':'What is a global maximum?','text':'A global maximum is simply the largest value of the function on its entire domain. A function may have many local maximums, but there can only be at most one global maximum. Since a global maximum is larger than everything it will be a local maximum so finding the global maximum is almost as easy as checking each local maximum as seeing which is the largest.<br><p><br> On a closed interval a function will have a global maximum, but if a function has a domain of all real numbers then it could grow larger and larger without bound and thus not have a global maximum. For instance, $f(x)=x$ has no global maximum on the domain all real numbers since the function can grow larger than any possible maximum. So we need to check the behavior of the function as $x$ approaches positive and negative infinity for any function with a domain of all real numbers.'})
	vparts.append({'header':'What does it mean when the question asks where a maximum is obtained?','text':'In general, you find local maximums by setting the derivative equal to zero and solving for $x$. Then each value is $x$ is checked to see if it is a max or min. So you can determine whether a maximum occurs without knowing what $f(x)$ is, but the maximum value is this $f(x)$ and not the value of $x$. If the question asks what the maximum value is then after finding $x$ you must pluf this into $f$. Often the question also asks where the maximum is obtained and this is asking for the value of $x$. Be careful to answer the question asked. You do not want to do all of the hard work of differentiation and solving only to get the correct answer to the wrong question.'})

	next_lesson = 'More about <a href="optimization_lesson.html">optimization.</a>'
	return render(request,'base_lesson.html',{'title':vtitle,'meta_des':meta_des,'LessonTitle':vLessonTitle,'Next':next_lesson,'Formal':vFormal,'Informal':vInformal,'Links':vLinks,'Flowchart':vFlowchart,'parts':vparts})

def optimization_lesson(request):
	vtitle = 'Optimization Word Problems - Calculus College'
	meta_des = "Do word problems about optimization scare you? Learn how to approach these problems so that you can solve almost anything your instructor throws your way."
	vLessonTitle = 'Optimization Problems'
	vFormal = '<h3 style="font-size:16px;">1. Generate a function with one variable. <br>2. Take the derivative. <br>3. Set the derivative equal to zero. <br>4. Determine the answer.</h3>'
	vInformal = 'Find constraint equations to eliminate all but one variable. Then differentiate with respect to this variable and determine when the derivative is zero.'
	vLinks = [{'href':'http://tutorial.math.lamar.edu/Classes/CalcI/Optimization.aspx','title':'Optimization','description':"Paul's Notes has an in-depth explanation with examples of using derivatives for optimization."}]
	vLinks.append({'href':'http://www.mathscoop.com/calculus/derivatives/applications/optimization-in-calculus.php','title':'Optimization Tutorial','description':"MathScoop works through many examples to show how and why derivatives are used for optimization."})
	vLinks.append({'href':'https://www.youtube.com/watch?v=Zq7g1nc2MJ8','title':'Optimization Problem','description':"PatrickJMT has a video walking through the solution to an optimization problem."})
	vFlowchart = 'static/img/optimization_flowchart.png'
	vparts = [{'header':'Where do I begin?','text':'From the problem write down as much information as possible. Define variables for any unknowns. Write down relevant equations. Determine what you need to optimize. You can always add more information as needed, but start by at least writing down something you know and something you need to find out.'}]
	vparts.append({'header':'What is my first goal?','text':'Every optimization word problem will end the same way. You want to create one equation that involves one variable so that you can differentiate and solve.<br><p><br> This might be simple if there is only one equation and one unknown. If you have more than one unknown then you will need to eliminate all but one variable with additional equations or formulas. Some equations may be given in the problem while others will require previous knowledge (generally simple geometric formulas like the area of a triangle). These equations are generally called constraints and involve at least two of your variables. '})
	vparts.append({'header':'How do I eliminate variables?','text':'Determine the equation that you need to optimize. The problem should have some final question. Turn this question into an equation using as many variables as necessary. If the question asks for the maximum area then create an equation to determine the area even if the equation depends on two or more variables. If the question asks for the minimum cost then create an equation for the cost.<br><p><br> Now if there is more than one variable you will need to find an equation that relates two or more variables in this equation. Generally the problem provides some sort of constraint like the sum of the height and length is less than some value. If the problem talks about perimeter you need to know that can used to create an equation with heights and lengths. Carefully read the problem to identify some information about what constraints there are on the variables.<br><p> Turn this information into an equation and solve that equation for one of the variables. In the equation you need to optimize, replace that variable with the equation in terms of another variable. Now the equation should depend on one fewer variable. Repeat this process until exactly one variable remains.'})
	vparts.append({'header':'What do I do once I have one equation?','text':'Once you have one equation with one variable then you can find <a href="maximums_minimums_lesson.html">the maximum or minimum</a> value. Take the derivative and set it equal to zero. Often with these problems there is only one such value and this is where the optimization occurs. But do be careful and make sure that you answer the question asked. Check that this value is a minimum or maximum and read exactly what form the answer should be. Just because you solved for some variable you denoted as $x$ does not mean you found the answer that your instructor wants.'})

	next_lesson = 'Learn to solve <a href="related_rates_lesson.html">Related Rates</a> problems.'
	return render(request,'base_lesson.html',{'title':vtitle,'meta_des':meta_des,'LessonTitle':vLessonTitle,'Next':next_lesson,'Formal':vFormal,'Informal':vInformal,'Links':vLinks,'Flowchart':vFlowchart,'parts':vparts})
def related_rates_lesson(request):
	vtitle = 'Related Rates - Calculus College'
	meta_des = "Do related rates problems frighten you? Become comfortable with these problems by learn everything you need to know to break them down."
	vLessonTitle = 'Related Rates'
	vFormal = '<h3 style="font-size:16px;">1. Find an equation relating all the rates. <br>2. Differentiate both sides.<br>3. Solve for the unknown rate.</h3>'
	vInformal = 'Find any rate that is given in the problem. Determine the rate you are asked to solve for. Find an equation that, after differentiating, relates these two (or more) rates. Solve for the rate you want.'
	vLinks = [{'href':'https://www.whitman.edu/mathematics/calculus_online/section06.02.html','title':'Related Rates','description':"Whitman College explains a few Related Rates example problems."}]
	vLinks.append({'href':'https://www.matheno.com/blog/4-steps-to-solve-related-rates-problem-part-1/','title':'4 steps to solve any related rates problem','description':"Matheno works through the most common related rates problems and shows you how to solve any problem on your own."})
	vLinks.append({'href':'https://www.khanacademy.org/math/ap-calculus-ab/derivative-applications-ab/related-rates-ab/v/falling-ladder-related-rates','title':'Related Rates','description':"A Khan Academy video working the standard falling ladder problem."})
	vFlowchart = 'static/img/related_rates_flowchart.png'
	vparts = [{'header':'Where do I begin?','text':'Read the problem and find a rate that is given. Write this rate in a form similar to $\\frac{dX}{dt}=R$ where $X$ is the variable that is changing and $R$ is the rate at which it is changing. Units are important, especially if multiple different scales are used, so make sure to include these in your equation. For instance, if the volume is increasing at a rate of $5$ feet per second then write down $\\frac{dV}{dt}=5\\frac{f}{s}$.'}]
	vparts.append({'header':'What do I do next?','text':'Read the problem and find the rate that you are asked to solve for. Write this rate in a form similar to $\\frac{dX}{dt}$ where $X$ is the variable that is changing at an unknown rate. For instance, if the question asks how fast the radius is increasing then note that you want to solve for $\\frac{dr}{dt}$.'})
	vparts.append({'header':'How do I use what I know to get what I want?','text':'We need to use the rate we know to determine the rate we are asked to find. So we need an equation that relates these two rates. Since rates are derivatives of functions what we need first is an equation that relates the two variables. We need to find an equation that involves the variable whose rate of change we know and the variable whose rate of change we want to know. For instance, if the question gives us the rate of change of the volume of a sphere and asks for the rate of change of the radius then we want an equation that involves $V$ and $r$. <br><p><br>Sometimes this equation will be somehow provided in the problem, but often we will need to know some geometric formula. Know the formulas for area and volume of basic shapes as well as the Pythagorean theorem. The volume of a sphere is $V=\\frac{4}{3}\pi r^3$, and this formula allows us to convert a rate involving volume to one involving radius or vice versa.'})
	vparts.append({'header':'How do I solve for the rate?','text':'Once you have the proper equation then you want to <a href="how_to_differentiate_lesson.html">differentiate this equation with respect to time</a>. You may have to use <a href="implicit_differentiation_lesson.html">implicit differentiation</a>, so make sure you differentiate both sides of the equation. Although $t$ will likely not appear in the equation, your variables are functions of $t$ so the <a href="chain_rule_lesson.html">chain rule</a> applies and both rates should appear after differentiating.<br><p><br>After differentiating you should be able to plug in every value you know and there will only be one unknown left. Solve for this rate and you are done. For instance, differentiating $V=\\frac{4}{3}\pi r^3$ yields $\\frac{dV}{dt}=3\\frac{4}{3}\pi r^2\\frac{dr}{dt}$. Then plug in the known rate of change of volume. At this point the only unknown left other than $\\frac{dr}{dt}$ is $r$, and you should be able to figure this out from the problem. The question should mention something about when to compute the rate of change. If the problem is meant to be easy then the radius will be given directly. If the problem is meant to be harder then you might be given the diamter or the volume of the sphere. Compute the radius from this information. Often you will reuse the equation that was differentiated to solve for the final variable.<br><p>Once the only unknown that remains is the rate you want to find then you can solve for that rate. Likely the equation will be a simple linear function of the rate so just divide by everything else. If the problems involves more than two rates, the process is the same but you will need to be given more information to plug in.  '})
	next_lesson = 'Learn how to solve some <a href="economics_lesson.html">Economics Problems.</a>'
	return render(request,'base_lesson.html',{'title':vtitle,'meta_des':meta_des,'LessonTitle':vLessonTitle,'Next':next_lesson,'Formal':vFormal,'Informal':vInformal,'Links':vLinks,'Flowchart':vFlowchart,'parts':vparts})
def economics_lesson(request):
	vtitle = 'Calculus in Economics - Calculus College'
	meta_des = "Learn how derivatives are used to calculate marginal cost, revenue, and profit so that you can solve your Economics problems with Calculus."
	vLessonTitle = 'Economic Applications'
	vFormal = "<h3 style='font-size:16px;'>$\\text{MC}=C'(x)$</h3>"
	vInformal = 'The marginal cost is the derivative of the cost function. And marginal revenue is the derivative of the revenue function.'
	vLinks = [{'href':'http://www.columbia.edu/itc/sipa/math/calc_econ_interp_u.html','title':'Economic Interpretation of Calculus operations','description':"Columbia University offers information about how Calculus can be used for Economics."}]
	vLinks.append({'href':'http://users.humboldt.edu/flashman/Presentations/HSU%20Colloquia/Calc&econ_12_03.html','title':'Making Calculus Sensible with Economics...','description':"Humboldt University offers explanations of the intersections of Calculus and Economics."})
	vLinks.append({'href':'https://www.youtube.com/watch?v=Cne4fdQX1sA','title':'Derivatives in Economics','description':"A video from njc314 about using derivatives to solve Economic problems."})
	vFlowchart = 'static/img/economics_flowchart.png'
	vparts = [{'header':'How do I calculate marginal cost?','text':'If you do not know the cost function then you must first determine that. Then take the derivative of the cost function. This function is the marginal cost function. To find the marginal cost at a particular value, input that value into the marginal cost function. Marginal revenue works exactly the same way with the revenue function.'}]
	vparts.append({'header':'How do I maximize profit?','text':'A common question in Economics is how many units to produce to create the maximum profit. If we have, or can create, formulas for cost and revenue then we can use derivatives to find this optimal quantity.<br><p><br> First, we need to know that profit maximization occurs when marginal cost equals marginal revenue. Producing additional units when marginal cost exceeds marginal revenue reduces profit so this intersection is important.<br><p>There are potentially five steps to consider. The first two steps are to get formulas for cost and revenue in terms of quantity. These formulas may be given or may need to be computed from supply and demand curves. Then the next two steps are to differentiate the cost and revenue functions to generate the marginal cost and marginal revenue functions. Finally set these two marginal functions equal to each other and solve for the optimal quantity. Check that the answer is actually a global maximum and make sure your answer is exactly what the question is asking for.'})
	vparts.append({'header':'Can I see an example?','text':'Your business knows that demand for its product is $q_d=1000-p$ and each additional unit costs $\$2$ to produce. What is the maximum profit that your business can achieve?<br><p><br> The cost function is easy to determine: $C(q)=2q$. The revenue function is the product of price times quantity sold so $R(q)=(1000-q)q$ since $p=1000-q$.<br><p>Thus the marginal cost is constant at $2$ and the marginal revenue is $-q+1000-q=1000-2q$ by the <a href="product_rule_lesson.html">product rule</a>.<br><p>Then we simply need to determine when $2$ equals $1000-2q$. The optimal quantity is hopefully $q=499$. And $q=499$ is a maximum by the <a href="second_derivative_lesson">second derivative test</a>. However, the question asks for the optimal profit. So we must determine the profit when 499 units are produced. The cost is $2\cdot 499=998$ and the revenue is $(1000-499)\cdot 499=249999$. The profit at this quantity is the difference, which is $\$249001 $.'})

	next_lesson = 'Learn how to solve some <a href="biology_lesson.html">Biology Problems.</a>'
	return render(request,'base_lesson.html',{'title':vtitle,'meta_des':meta_des,'LessonTitle':vLessonTitle,'Next':next_lesson,'Formal':vFormal,'Informal':vInformal,'Links':vLinks,'Flowchart':vFlowchart,'parts':vparts})
def biology_lesson(request):
	vtitle = 'Calculus in Biology - Calculus College'
	meta_des = "Learn how derivatives are used to calculate how fast a population is growing. Learn to differentiate exponential and logistic growth functions."
	vLessonTitle = 'Biology Applications'
	vFormal = '<h3 style="font-size:16px;">$\\frac{d}{dt}[Ce^{kt}]=kCe^{kt}$<br>$\\frac{d}{dt}[\\frac{L}{1+Ce^{-kt}}]=\\frac{kLCe^{-kt})}{(1+Ce^{-kt})^2}$</h3>'
	vInformal = 'Differentiate the population function to determine how quickly the population is growing at any time.'
	vLinks = [{'href':'http://www.brynmawr.edu/math/people/vandiver/BiologicalapplicationstoincorporateintoCalculus.htm','title':'Biological Applications in Calculus','description':"Bryn Mawr College offers applications of Calculus for those interested in Biology."}]
	vLinks.append({'href':'https://www.youtube.com/watch?v=vwMsLwbUSJw','title':'Significance of Calculus in Biology','description':"A video from Bre'Ann Baskett about using Calculus for Biology."})
	vLinks.append({'href':'http://www-eve.ucdavis.edu/sschreiber/reprints/MAA.pdf','title':'Motivating Calculus with Biology','description':"Course notes from UC Davis that explain how Biology uses Calculus."})
	vFlowchart = 'static/img/biology_flowchart.png'
	vparts = [{'header':'How do I calculate how quickly a population is growing?','text':'A population grows exponentially and you are asked to determine how fast the population is growing at a certain point in time. Growth really means change and change is code for take the derivative. Take the derivative of the population function and evaluate at the given time.'}]
	vparts.append({'header':'What if the population function is not given?','text':'The above step is usually all the Calculus required and since the functions are often exponential the derivative is not too hard. To make a question more difficult you may not be given the population function but still asked to find the rate of growth function. The first step in this case is to find the population function.<br><p><br>How to find the population function is going to depend on what information is given to you. You are going to need to find the initial value of the population and the rate at which it grows. If you know the population at two different times you can plug in these two points and determine the rate. Then you can find the initial value by using one point and the rate to solve for $P_0$. Then just plug everything into the appropriate formula.'})
	vparts.append({'header':'How do I calculate when a population is growing at a certain speed?','text':'Sometimes a question will ask when a population is growing at a rate of $10$ feet per second or some other value. The process begins the same way by taking the derivative of the population function. But if you are not given a time then you cannot simply plug into this derivative.<br><p><br>Instead you must solve for the time. You can compute the growth at any time, and you want to know at what time the growth is a certain speed. Thus you will set the derivative equal to the given speed and solve for $t$. Because $t$ is likely in the exponent you will probably need to take a natural logarithm to solve, but if you remember your properties of logarithms then this should be easy enough.'})
	vparts.append({'header':'What if the population does not grow exponentially?','text':'Not every population grows in a purely exponential fashion. A popular model for population is the logistic growth function. You will still follow the same process, but the function will look like $P=\\frac{L}{1+Ce^{-k(t)}}$ instead of $P=Ce^{kt}$. Logistic growth is a function that starts as almost exponential growth, but at some point the growth slows until it approaches some carrying capacity. Very few populations can grow exponentially forever so we need to use slightly more complicated functions to model them. However, the logistic growth function is still not too hard to differentiate, and the rest of the process is still the same.'})
	
	next_lesson = 'Learn how to compute <a href="velocity_lesson.html">velocity.</a>'
	return render(request,'base_lesson.html',{'title':vtitle,'meta_des':meta_des,'LessonTitle':vLessonTitle,'Next':next_lesson,'Formal':vFormal,'Informal':vInformal,'Links':vLinks,'Flowchart':vFlowchart,'parts':vparts})
def velocity_lesson(request):
	vtitle = 'Velocity as a Derivative - Calculus College'
	meta_des = "Learn how to compute the velocity of a function by taking a derivative. Also understand acceleration and how to parse word problems."
	vLessonTitle = 'Velocity'
	vFormal = "<h3 style='font-size:16px;'>$v(t)=p'(t)$<br>$a(t)=v'(t)=p''(t)$</h3>"
	vInformal = 'The velocity function is the derivative of the position function. Acceleration is the second derivative of position (and hence also the derivative of velocity.'
	vLinks = [{'href':'https://www.varsitytutors.com/calculus_1-help/how-to-find-velocity','title':'How to find Velocity','description':"Varsity Tutors has a few example problems involving taking derivatives to find velocity."}]
	vLinks.append({'href':'https://www.youtube.com/watch?v=pFeuGMMiZWw','title':'Position, Velocity, Acceleration using Derivatives','description':"A viedo from PatrickJMT about how these three functions are related by differentiation."})
	vLinks.append({'href':'https://www.youtube.com/watch?v=BMECS79zFmo','title':'How to use Derivatives to find Velocity','description':"StraighterLine has a video that finds the velocity using derivatives."})
	vFlowchart = 'static/img/velocity_flowchart.png'
	vparts = [{'header':'How do I compute the velocity at given time?','text':'Velocity is the rate of change of a function. And rate of change is code for take a derivative. The velocity of an object is the derivative of the position function.<br><p><br>You should have been given some function that models the position of the object. Take the derivative of this function. Then you can plug in the time at which you are asked to find the velocity. It really is that simple if you always keep in mind that velocity is the derivative of position.'}]
	vparts.append({'header':'How do I compute the acceleration at a given time?','text':'Acceleration is the rate of change of the velocity of a function. Thus you want to take the second derivative of the position function.'})
	vparts.append({'header':'What if the question asks when the velocity reaches a certain value?','text':'If the question asks when something occurs then we are going to need to solve for $t$. We still take the derivative of the position function, but instead of plugging in directly for $t$ we set the derivative equal to the given velocity. Then solve for $t$ and this is the time at which the velocity reaches the desired value.<br><p><br> Often you will be asked to determine when the velocity is 0 because this is the time at which the object changes direction. In addition an added twist could be to ask where the object is when the velocity is 0. In this case it is neccessary to solve for the time first, but then plug this time into the position function.'})
	vparts.append({'header':'Can I see an example?','text':"The most common questions involve tossing an object in the air. For these questions the acceleration will be constant so the position function will be a quadratic function and the derivative will be quite simple. For example, assume a ball's position is given by the function $p(t)=-4.9t^2+10t+2$. What is the maximum height of the ball?<br><p><br>At the maximum height the ball will not be rising or falling so it will have 0 velocity. Thus we need to compute $v(t)$ and set it equal to 0. Take the derivative and you should get $v(t)=p'(t)=-9.8t+10$. Thus the maximum height will occur when $t=\\frac{10}{9.8}$, and if you plug this value into $p(t)=-4.9t^2+10t+2$ you will have your answer."})
	next_lesson = '<!-- <a href="_lesson.html"></a>-->More lessons coming soon.'
	return render(request,'base_lesson.html',{'title':vtitle,'meta_des':meta_des,'LessonTitle':vLessonTitle,'Next':next_lesson,'Formal':vFormal,'Informal':vInformal,'Links':vLinks,'Flowchart':vFlowchart,'parts':vparts})
def tangent_line_lesson(request):
	vtitle = 'Tangent Lines - Calculus College'
	meta_des = "Learn to use derivatives to find the tangent line to a curve. Implicit functions and normal lines are covered as well."
	vLessonTitle = 'Tangent Lines'
	vFormal = "<h3 style='font-size:16px;'>$y=f'(x_0)(x-x_0)+f(x_0)$</h3>"
	vInformal = 'The slope of the tangent line is the derivative evalutated at the x-coordinate.'
	vLinks = [{'href':'','title':'','description':""}]
	vLinks.append({'href':'','title':'','description':""})
	vLinks.append({'href':'','title':'','description':""})
	vFlowchart = 'static/img/tangent_line_flowchart.png'
	vparts = [{'header':'What is the tangent line?','text':'A tangent line is a line that just touches a curve without passing through. The slope of the tangent line is the instantaneous rate of change of the curve at that point. Since the derivative calculates the instantaneous rate of change we will take a derivative to determine the slope of the tangent line.'}]
	vparts.append({'header':'How can I compute the slope of the tangent line?','text':'You should be given at least teo pieces of information. The function and the x-ccordinate at which to find the tangent line. Every point on the curve will have a different tangent line. We want to find the equation of a line so knowing the slope is neccessary.<br><p><br>Slope is code for derivative so the first step is to differentiate the function. We only need to know the slope at one point so we then plug in the x-coordinate of the point we are told to worry about. The derivative at this point is the slope of the tangent line. '})
	vparts.append({'header':'How do find the equation of the tangent line?','text':"Once you have the slope you only need a point on the line to determine the equation. The only point that we know is on the line is the point on the curve that the tangent line pases through. So use the coordinates of this point and plug everything into point-slope form to get the equation. The point-slope form of the equation of a line is $y=m(x-x_0)+y_0$ where $(x_0,y_0)$ is the point and $m$ is the slope. If you only know the x-coordinate then $y_0=f(x_0)$ so the tangent line to the curve is $y=f'(x_0)(x-x_0)+f(x_0)$. "})
	vparts.append({'header':'What is the normal line?','text':"The normal line to a curve is the line that is perpendicular to curve when it passes directly through a point. The normal line has applications related to various forces in Physics. The equation of the normal line is almost the same as the equation of the tangent line, but the slope of the normal line is the negative reciprocal of the slope of the tangent line. Thus, $y=\\frac{-1}{f'(x_0)}(x-x_0)+f(x_0)$ is the equation of the normal line at the point $(x_0,f(x_0))$. You don't need to memorize both of these formulas but instead know the point-slope form and how to compute the slopes of the tangent and normal lines."})
	vparts.append({'header':'What if the function is defined implicitly?','text':'For a function that is defined implicitly we need to know the function, the x-coordinate, and the y-coordinate in order to find the equation of the tangent line. However, the process is exactly the same. Find the derivative implicitly. Then find the slope by inserting the given values of $x$ and $y$ into the derivative. Then we have the slope as well as a point so we can use point-slope form to get the equation of the tangent line.'})
	next_lesson = ' <a href="_lesson.html"></a>'
	return render(request,'base_lesson.html',{'title':vtitle,'meta_des':meta_des,'LessonTitle':vLessonTitle,'Next':next_lesson,'Formal':vFormal,'Informal':vInformal,'Links':vLinks,'Flowchart':vFlowchart,'parts':vparts})
def linear_approximation_lesson(request):
	vtitle = 'Linear Approximation - Calculus College'
	meta_des = "Use tangent lines to approximate the value of a function near a known point. "
	vLessonTitle = 'Linear Approximation'
	vFormal = "<h3 style='font-size:16px;'>$f(x_0+\epsilon )~f(x_0)+\epsilon f'(x_0)$</h3>"
	vInformal = 'We can approximate the value of a function at a point if we know the value of the function and its derivative at a nearby point by computing the tangent line.'
	vLinks = [{'href':'','title':'','description':""}]
	vLinks.append({'href':'','title':'','description':""})
	vLinks.append({'href':'','title':'','description':""})
	vFlowchart = ''
	vparts = [{'header':'What is the square root of 17?','text':'We know that the square root of 16 is 4 so we can assume that the square root of 17 is slightly larger than 4. Linear approximation uses tangent line to make our guess more precise. We can compute the tangent line to the square root function at $x=16$ and then evaluate the tangent line at $x=17$. Since the tangent line is close to the curve around this point we should get a decent approximation. The tangent line is $y=\\frac{1}{8}(x-16)+4$. Thus the square root of 17 is approximately 4.125. We were able to make this approximation without taking any square roots except the square root of 16 which we know.'}]
	vparts.append({'header':'Does this process work for any function?','text':"Yes. You can always make an approximation of a function if you know the value of the function and its derivative at a nearby point. If you want to approximate the value of $f(x_1)$ you need to determine $f(x_0)$ and $f'(x_0)$ where $x_0$ is as close as possible to $x_1$. Then $f(x_1)~f'(x_1)(x_1-x_0)+f(x_0)$."})
	vparts.append({'header':'What are the limitations?','text':'Linear approximation only gives sufficently close approximation when there is a known value that is sufficiently close. Functions that are not close to linear will lead to poor approximations for even fairly close values. Depending on how precise your approximation needs to be, it might not be worth it to use linear approximation.'})
	vparts.append({'header':'How can we make this approximation better?','text':'As we get farther from our known point the tangent line is likely getting farther from the actual value. Thus we can get a better approximation if we knew a square root of a value that is closer to 17. Of course, you probably do not know the square root of 16.5 or any other number between 16 and 17 so we will have to approximate this value.'})
	vparts.append({'header':'Can I see some more examples?','text':"Linear approximation problems most often use function that are easy to compute for a few values of $x$ but not all. So polynomials rarely appear since there are easier ways to calculate the value of a polynomial and really complicated functions will not appear becuase no values are known. Trigonometric functions and square roots are most commonly used.<br><p><br>We've already worked a square root so let's see a trigonometric function. Approximate $\cos(3)$. For this example we want to use $x_0=\pi$ because we know $\cos(\pi)$. We must now compute the derivative of $\cos(x)$ at $x_0=\pi$. The derivative of $\cos(x)$ is $-\sin(x)$ and $-\sin(\pi)=0"})
	next_lesson = ' <a href="_lesson.html"></a>'
	return render(request,'base_lesson.html',{'title':vtitle,'meta_des':meta_des,'LessonTitle':vLessonTitle,'Next':next_lesson,'Formal':vFormal,'Informal':vInformal,'Links':vLinks,'Flowchart':vFlowchart,'parts':vparts})
def newton_method_lesson(request):
	vtitle = "Newton's Method - Calculus College"
	meta_des = "Learn how to use Newton's method to approximate the value of a function by taking derivatives."
	vLessonTitle = "Newton's Method"
	vFormal = '<h3 style="font-size:16px;"></h3>'
	vInformal = 'Use linear approximation repeatedly on smaller intervals.'
	vLinks = [{'href':'','title':'','description':""}]
	vLinks.append({'href':'','title':'','description':""})
	vLinks.append({'href':'','title':'','description':""})
	vFlowchart = 'static/img/newton_method_flowchart.png'
	vparts = [{'header':'What is the square root of 17?','text':'Using linear approximation we estimated the square root of 17 to be 4.125. We want an even better approximation. Instead of using one tangent line we will repeatedly create tangent lines that provide closer approximations. If we knew the square root of 16.5 then we could produce a better approximation of 17 so we will use ilinear approximation to estimate the square root of 16.5 first.<br><p><br>The square root of 16.5 is about $\\frac{1}{8}(16.5-16)+4=4.0625$. Then we approximate $\sqrt{17}$ using this approximation. '}]
	vparts.append({'header':'','text':''})
	next_lesson = ' <a href="_lesson.html"></a>'
	return render(request,'base_lesson.html',{'title':vtitle,'meta_des':meta_des,'LessonTitle':vLessonTitle,'Next':next_lesson,'Formal':vFormal,'Informal':vInformal,'Links':vLinks,'Flowchart':vFlowchart,'parts':vparts})
def lhopital_lesson(request):
	vtitle = "L'Hospital's Rule - Calculus College"
	meta_des = "Learn to take limits of indeterminate forms using derivatives with L'Hospital's Rule because you cannot divide by 0."
	vLessonTitle = "L'Hospital's Rule"
	vFormal = '<h3 style="font-size:16px;">\lim_{x}</h3>'
	vInformal = 'If the limit is an indeterminate form like $\\frac{0}{0}$ or $\\frac{\infty}{\infty}$ then differentiate the numerator and denominator and take the limit.'
	vLinks = [{'href':'','title':'','description':""}]
	vLinks.append({'href':'','title':'','description':""})
	vLinks.append({'href':'','title':'','description':""})
	vFlowchart = 'static/img/lhopital_flowchart.png'
	vparts = [{'header':"When can we use L'Hospital's Rule?",'text':"Only use L'Hospital's rule when taking the limit results in an indeterminate form. If the limit is $\\frac{0}{0}$ or $\\frac{\infty}{\infty}$ then the limit cannot be determined from this information alone so we need to use L'Hospital's Rule. "}]
	vparts.append({'header':"How do we use L'Hospital's Rule?",'text':''})
	next_lesson = ' <a href="_lesson.html"></a>'
	return render(request,'base_lesson.html',{'title':vtitle,'meta_des':meta_des,'LessonTitle':vLessonTitle,'Next':next_lesson,'Formal':vFormal,'Informal':vInformal,'Links':vLinks,'Flowchart':vFlowchart,'parts':vparts})
def sketch_graph_lesson(request):
	vtitle = ' - Calculus College'
	meta_des = ""
	vLessonTitle = ''
	vFormal = '<h3 style="font-size:16px;"></h3>'
	vInformal = ''
	vLinks = [{'href':'','title':'','description':""}]
	vLinks.append({'href':'','title':'','description':""})
	vLinks.append({'href':'','title':'','description':""})
	vFlowchart = ''
	vparts = [{'header':'','text':''}]
	vparts.append({'header':'','text':''})
	next_lesson = ' <a href="_lesson.html"></a>'
	return render(request,'base_lesson.html',{'title':vtitle,'meta_des':meta_des,'LessonTitle':vLessonTitle,'Next':next_lesson,'Formal':vFormal,'Informal':vInformal,'Links':vLinks,'Flowchart':vFlowchart,'parts':vparts})
def tangent_line_lesson(request):
	vtitle = ' - Calculus College'
	meta_des = ""
	vLessonTitle = ''
	vFormal = '<h3 style="font-size:16px;"></h3>'
	vInformal = ''
	vLinks = [{'href':'','title':'','description':""}]
	vLinks.append({'href':'','title':'','description':""})
	vLinks.append({'href':'','title':'','description':""})
	vFlowchart = ''
	vparts = [{'header':'','text':''}]
	vparts.append({'header':'','text':''})
	next_lesson = ' <a href="_lesson.html"></a>'
	return render(request,'base_lesson.html',{'title':vtitle,'meta_des':meta_des,'LessonTitle':vLessonTitle,'Next':next_lesson,'Formal':vFormal,'Informal':vInformal,'Links':vLinks,'Flowchart':vFlowchart,'parts':vparts})

