from django.shortcuts import render


def what_are_integrals_lesson(request):
    vtitle = 'What are Integrals? - Calculus College'
    meta_des = 'If you spend a little time learning what an integral represents then you will get better at taking integrals. Understand the notation and the rest will follow.'
    vLessonTitle = 'Learn about Integrals'
    vFormal = "<h3>$f'(c)=\lim_{x\\rightarrow c}\\frac{f(x)-f(c)}{x-c}$</h3>"
    vInformal = 'The integral of a function is the area under the curve of the function. Think about area when dealing with integrals.'
    vLinks = [{'href':'https://betterexplained.com/articles/calculus-building-intuition-for-the-derivative/','title':'Calculus: Building Intuition for the Derivative','description':"Better Explained provides an intuitive explanation of derivatives."}]
    vLinks.append({'href':'https://www.khanacademy.org/math/calculus-home/taking-derivatives-calc/intro-to-diff-calculus-calc/a/derivative-notation-review','title':'Derivative Notation Review','description':'Khan Academy review of notation used in differentiation.'})
    vLinks.append({'href':'http://patrickjmt.com/understanding-the-definition-of-the-derivative/','title':'What is a Derivative? Understanding the Definition','description':'PatrickJMT explains the basics of derivatives.'})
    vFlowchart = 'https://media.giphy.com/media/PET1RBa0nfzDa/source.gif'
    vparts = [{'header':'What is the derivative of a function?','text':'The derivative is a function that outputs the instantaneous rate of change of the original function. Instanstaneous means analyzing what happens when there is zero change in the input so we must take a limit to avoid dividing by zero. Fortunately mathematicians have developed many rules for differentiation that allow us to take derivatives without repeatedly computing limits. However, remembering that the derivative is a limit is often beneficial, especially when applying the derivative to solve word problems.<br>'}]
    vparts.append({'header':'What do all these symbols mean?','text':"There are two popular ways to denote the derivative of a function: $f'(x)$ and $\\frac{d}{dx}[f(x)]$. Each notation has advantages and can be used when most appropriate. The notation $f'(x)$ is short and to the point which is why this form is seen often in most Calculus courses. However, there are two main disadvantages. <br><p><br>With $f'(x)$ the variable of differentation is not always clear and the function must be defined separately. In order to ask for the derivative of something like $x^2$ you must first define that $f(x)=x^2$ rather than simply asking for $\\frac{d}{dx}[x^2]$. And remember that differentation is always taken with respect to some variable, usually but not always $x$, and $f'(x)$ does not always make it clear what this variable is. What is $f'(3)$? Answering this question requires knowing $f$ and knowing the independent variable of $f$. Of course, there is not a nice way of asking for $f'(3)$ in $\\frac{d}{dx}$ notation.<p>The notation $\\frac{dy}{dx}$ stands for the derivative of $y$ with respect to $x$. And $\\frac{d}{dx}[f(x)]$ stands for the derivative of $f(x)$ (or whatever function is inside the brackets) with respect to $x$. This notation is often used to ask for a derivative without defining extra functions or when the variable of differentiation is an important part of the question.<p>Do not be scared away by either notation. Understanding the notation may seem unneccessary, but very few students succeed at Calculus without learning what a derivative really is and what the notation means."})
    next_lesson = 'Learn <a href="how_to_differentiate_lesson.html">How to Take Derivatives</a>'
    return render(request,'base_lesson.html',{'title':vtitle,'meta_des':meta_des,'LessonTitle':vLessonTitle,'Next':next_lesson,'Formal':vFormal,'Informal':vInformal,'Links':vLinks,'Flowchart':vFlowchart,'parts':vparts})
