from landing import views as landing_views
from django.conf.urls import url, include

#from django.contrib import admin

urlpatterns = [
    # Examples:
    url(r'^sitemap.xml$', landing_views.sitemap, name="sitemap"),
    url(r'^robots.txt$', landing_views.robots, name="robots"),

    # url(r'^blog/', include('blog.urls')),
    url(r'^$',landing_views.home_page, name='home'),
    #url(r'^derivativecalculatorwrong.html', landing_views.wrong, name='dc'),
    #url(r'^derivativecalculator.html', landing_views.calculator, name='dc'),
    #url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^signup-beta.html',landing_views.signup, name='signup'),
    url(r'^login.html',landing_views.login_page, name='login'),
    url(r'^charge.html',landing_views.charge_page, name='charge'),
    #url(r'^admin/', include(admin.site.urls)),
    url(r'^worksheets.html',landing_views.worksheets, name='worksheets'),
    url(r'^swipe.html',landing_views.swipe, name='swipe'),
    url(r'^swipeIntegral.html',landing_views.swipeIntegral, name='swipeIntegral'),
    url(r'^videoDerivative.html',landing_views.videoDerivative, name='videoDerivative'),
    url(r'^videoRiemann.html',landing_views.videoRiemann, name='videoRiemann'),
    url(r'^videoTangent.html',landing_views.videoTangent, name='videoTangent'),
    url(r'^videoTrig.html',landing_views.videoTrig, name='videoTrig'),
    url(r'^videoNewton.html',landing_views.videoNewton, name='videoNewton'),
    url(r'^videoIntegral.html',landing_views.videoIntegral, name='videoIntegral'),
    url(r'^videoRelated.html',landing_views.videoRelated, name='videoRelated'),
    url(r'^videoSearch.html',landing_views.videoSearch, name='videoSearch'),
    url(r'^videoIndex.html',landing_views.videoIndex, name='videoIndex'),
    url(r'^about.html',landing_views.about, name='about'),
    url(r'^apiDerivative.html',landing_views.apiDerivative, name='apiDerivative'),
    url(r'^apiIntegral.html',landing_views.apiIntegral, name='apiIntegral'),
    url(r'^apiTangent.html',landing_views.apiTangent, name='apiTangent'),
    url(r'^apiRiemann.html',landing_views.apiRiemann, name='apiRiemann'),
    #url(r'^apiTrig.html',landing_views.apiTrig, name='apiTrig'),
    url(r'^apiNewton.html',landing_views.apiNewton, name='apiNewton'),
    url(r'^derivatives_lesson.html',landing_views.derivatives_lesson, name='derl'),
    #url(r'^derivative_applications_lesson.html',landing_views.derivative_applications_lesson, name='dal'),
    url(r'^derivative_calculator.html',landing_views.derivative_calculator, name='dc'),
    url(r'^integral_calculator.html',landing_views.integral_calculator, name='ic'),

    url(r'^trigInteractive.html',landing_views.trigInteractive, name='trigint'),
    url(r'^riemannInteractive.html',landing_views.riemannInteractive, name='reiint'),
    url(r'^riemannInteractiveFixed.html',landing_views.riemannInteractiveFixed, name='reiint'),

    url(r'^power_rule_worksheet.html',landing_views.power_rule_worksheet, name='prw'),
    url(r'^product_rule_worksheet.html',landing_views.product_rule_worksheet, name='prodw'),
    url(r'^chain_rule_worksheet.html',landing_views.chain_rule_worksheet, name='crw'),
    url(r'^sum_rule_worksheet.html',landing_views.sum_rule_worksheet, name='srw'),
    url(r'^quotient_rule_worksheet.html',landing_views.quotient_rule_worksheet, name='qrw'),
    url(r'^trigonometric_functions_worksheet.html',landing_views.trigonometric_functions_worksheet, name='tfw'),
    url(r'^exponentials_logarithms_worksheet.html',landing_views.exponentials_logarithms_worksheet, name='explogw'),
    url(r'^logarithmic_differentiation_worksheet.html',landing_views.logarithmic_differentiation_worksheet, name='logdw'),
    url(r'^all_derivatives_worksheet.html',landing_views.all_derivatives_worksheet, name='alldw'),

    url(r'^implicit_differentiation_worksheet.html',landing_views.implicit_differentiation_worksheet, name='idw'),
    url(r'^increasing_decreasing_worksheet.html',landing_views.increasing_decreasing_worksheet, name='idw'),
    url(r'^second_derivative_worksheet.html',landing_views.second_derivative_worksheet, name='sdw'),
    url(r'^optimization_worksheet.html',landing_views.optimization_worksheet, name='ow'),
    url(r'^related_rates_worksheet.html',landing_views.related_rates_worksheet, name='rrw'),
	
    url(r'^power_rule_lesson.html',landing_views.power_rule_lesson, name='prl'),
    url(r'^product_rule_lesson.html',landing_views.product_rule_lesson, name='prodl'),
    url(r'^chain_rule_lesson.html',landing_views.chain_rule_lesson, name='chl'),
    url(r'^sum_rule_lesson.html',landing_views.sum_rule_lesson, name='srl'),
    url(r'^quotient_rule_lesson.html',landing_views.quotient_rule_lesson, name='qrl'),
    url(r'^logarithmic_differentiation_lesson.html',landing_views.logarithmic_differentiation_lesson, name='ldl'),
    url(r'^what_are_derivatives_lesson.html',landing_views.what_are_derivatives_lesson, name='wdl'),
    url(r'^exponentials_logarithms_lesson.html',landing_views.exponentials_logarithms_lesson, name='ell'),
    url(r'^trigonometric_functions_lesson.html',landing_views.trigonometric_functions_lesson, name='tfl'),
    url(r'^how_to_differentiate_lesson.html',landing_views.how_to_differentiate_lesson, name='htdl'),

    url(r'^implicit_differentiation_lesson.html',landing_views.implicit_differentiation_lesson, name='idl'),
    url(r'^concavity_lesson.html',landing_views.concavity_lesson, name='conl'),
    url(r'^second_derivatives_lesson.html',landing_views.second_derivatives_lesson, name='sdl'),
    url(r'^increasing_decreasing_lesson.html',landing_views.increasing_decreasing_lesson, name='idl'),
    url(r'^tangent_line_lesson.html',landing_views.tangent_line_lesson, name='tll'),
    url(r'^maximums_minimums_lesson.html',landing_views.maximums_minimums_lesson, name='mml'),
    url(r'^optimization_lesson.html',landing_views.optimization_lesson, name='optl'),
    url(r'^related_rates_lesson.html',landing_views.related_rates_lesson, name='rrl'),
    url(r'^economics_lesson.html',landing_views.economics_lesson, name='ecol'),
    url(r'^biology_lesson.html',landing_views.biology_lesson, name='biol'),
    url(r'^velocity_lesson.html',landing_views.velocity_lesson, name='vell'),

    url(r'^power_rule_integral_lesson.html',landing_views.power_rule_integral_lesson, name='prl'),
    url(r'^sum_rule_integral_lesson.html',landing_views.sum_rule_integral_lesson, name='srl'),
    url(r'^what_are_integrals_lesson.html',landing_views.what_are_integrals_lesson, name='wdl'),
    url(r'^exponentials_integral_lesson.html',landing_views.exponentials_integral_lesson, name='ell'),
    url(r'^trigonometric_functions_integral_lesson.html',landing_views.trigonometric_functions_integral_lesson, name='tfl'),
    url(r'^how_to_integrate_lesson.html',landing_views.how_to_integrate_lesson, name='htdl'),
    url(r'^u_substitution_lesson.html',landing_views.u_substitution_lesson, name='usub'),
    url(r'^integration_by_parts_lesson.html',landing_views.integration_by_parts_lesson, name='ibp'),
    url(r'^partial_fractions_lesson.html',landing_views.partial_fractions_lesson, name='pf'),
    url(r'^definite_integrals_lesson.html',landing_views.definite_integrals_lesson, name='di'),

    url(r'^derivative_worksheets.html',landing_views.derivative_worksheets, name='derw'),
    url(r'^calculus_worksheets.html',landing_views.calculus_worksheets, name='calcw'),
    url(r'^help.html',landing_views.help, name='help'),
    url(r'^privacy.html',landing_views.privacy, name='privacy'),
    url(r'^terms.html',landing_views.terms, name='terms'),
    url(r'^contact.html',landing_views.contact, name='contact'),
    url(r'^index.html', landing_views.home_page, name='home'),
    url(r'^google7c27786bf8d16e84.html', landing_views.google, name='google'),
    url(r'^loaderio-69e38ad0d17e17755663496f5eb3b2f4.html', landing_views.loaderio, name='loaderio'),
    #url(r'^images/', landing_views.images, name='images'),
]

